using MyMechanicShop.EntityFrameworkCore;
using Xunit;

namespace MyMechanicShop.EntityFrameworkCore;

public class MyMechanicShopEntityFrameworkCoreCollectionFixtureBase : ICollectionFixture<MyMechanicShopEntityFrameworkCoreFixture>;
